### ISSUE TITLE
Allow volunteers to subscribe to the Higher Education Engagement project

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/higher-education-engagement#3]
# Context 

We want to allow GSF volunteers to subscribe to the project.

# Actions

- [x] @seanmcilroy29 setup a new Google Group - "higher-education-engagement@"
- [x] @seanmcilroy29 Add project to [project subscription list](https://greensoftware.foundation/subscribe/)

**Comment by seanmcilroy29** [comment]
@russelltrow 
- [x] setup a new Google Group - "higher-education-engagement@"
- [x] Add project to [project subscription list](https://greensoftware.foundation/subscribe/)
- [x] @russelltrow - Group manager

Submission form was tested and is working ok
